# Taken from Leukocyte (https://github.com/NucleoidMC/leukocyte/blob/main/.github/workflows/release.yml)

name: Fabric Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload GitHub release
        uses: AButler/upload-release-assets@v3
        with:
          files: 'build/libs/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}